export const MODAL_VISIBILITY = "MODAL_VISIBILITY"

export const DRAWER_VISIBILITY = "DRAWER_VISIBILITY"

export const SIDEBAR_FLAG = "SIDEBAR_FLAG";

export const MYSQL_MONITOR_SELECT_START_DATE = 'MYSQL_MONITOR_SELECT_START_DATE';

export const MYSQL_MONITOR_SELECT_END_DATE = 'MYSQL_MONITOR_SELECT_END_DATE';